#!/bin/bash
# Deploy the Claude Code base config into a project.
# Usage: deploy/claude-config.sh <project-dir>
#
# Copies the portable parts of this repo (.claude/skills, .claude/settings.json
# and scripts/hooks) into <project-dir>.
# settings.local.json is intentionally NOT copied (machine/project-specific).
# .claude/commands/opsx is generated by `openspec init` — run it in the target
# project instead of copying.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

if [ $# -ne 1 ]; then
    echo "Usage: $0 <project-dir>" >&2
    exit 1
fi

DEST="$1"
if [ ! -d "$DEST" ]; then
    echo "Error: '$DEST' is not a directory" >&2
    exit 1
fi

mkdir -p "$DEST/.claude/skills" "$DEST/scripts/hooks"

cp -r "$REPO_ROOT/.claude/skills/." "$DEST/.claude/skills/"
cp    "$REPO_ROOT/scripts/hooks/"*.py "$DEST/scripts/hooks/"

if [ -f "$DEST/.claude/settings.json" ]; then
    echo "Note: $DEST/.claude/settings.json already exists — left untouched."
    echo "      Merge the 'hooks' block from $REPO_ROOT/.claude/settings.json manually."
else
    cp "$REPO_ROOT/.claude/settings.json" "$DEST/.claude/settings.json"
fi

echo "Claude Code base config deployed to $DEST"
